" Basics
set nocompatible
set number

" Folding
set foldmethod=indent
set colorcolumn=81
"set foldlevel=1
"set foldclose=all

syntax on
match error "\s$"

au BufRead /tmp/mutt-* set tw=72

" Folding shortcut
nnoremap <Tab> za

" Tab navigation
nnoremap <C-h> :tabprevious<CR>
nnoremap <C-l> :tabnext<CR>

" Moving tabs
nnoremap <C-k> :tabm +1<CR>
nnoremap <C-j> :tabm -1<CR>

filetype plugin on

autocmd Filetype python setlocal tabstop=4 shiftwidth=4 softtabstop=4
autocmd Filetype ada setlocal tabstop=3 shiftwidth=3 softtabstop=3

let g:netrw_banner = 0
let g:netrw_liststyle = 4
let g:netrw_browse_split = 3
let g:netrw_altv = 1
let g:netrw_winsize = 15
augroup ProjectDrawer
  autocmd!
  autocmd VimEnter * :Vexplore
augroup END
