#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# START ssh-agent if not already started
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent > ~/.ssh-agent-thing
fi
if [[ "$SSH_AGENT_PID" == "" ]]; then
    eval "$(<~/.ssh-agent-thing)"
fi

PS1='\[\e[0;32m\]\u\[\e[m\]\[\e[1;34m\]\w\[\e[m\]\[\e[1;32m\] $?\$ \[\e[m\]\[\e[1;37m\]'
#PS1='[\u@\h \W]$?\$ '

# Eiffel IDE config lines
HEPTC_PATH=/home/ferryk/.opam/4.02.3/bin

export ISE_EIFFEL=$HOME/Eiffel_15.12
export ISE_PLATFORM=linux-86-64
export PATH=$PATH:$ISE_EIFFEL/studio/spec/$ISE_PLATFORM/bin:$QUARTUS_PATH:$HEPTC_PATH
export MATLAB_JAVA="/usr/lib/jvm/java-8-openjdk/jre"

# set the TERM variable to a color-enabled type (xterm-color)
export TERM="xterm-color"
export VISUAL="vim"
export PATH=/opt/sparc-unknown-linux-gnu/bin:$PATH
export KSRC=~/linux/src
export __OLD__KSRC=~/linux/src
export KBUILD_OUTPUT=~/linux/build
export __OLD__KBUILD_OUTPUT=~/linux/build

# ROOTFS
export ARCH_ROOTFS=/home/ferryk/archlinux_rootfs
export LAVA_ROOTFS=/home/ferryk/debian_rootfs

eval $(dircolors ~/.dircolors)

# FUNCTIONS

start_vm() {

  sudo libvirtd -d &&  \
  sudo systemctl start nfs-server &&  \
  sudo systemctl start virtlogd.socket
}

adjust_screen() {
	xrandr --output HDMI1 --$1-of eDP1 --mode 1920x1080
}

greph() {
	grep -Irn $1 . | vim -R -
}

lock() {
	$HOME/./.alt_lock.sh
}

backup() {
	sudo dd if=/dev/sda of=$1 bs=1M status=progress
}

kernel_cc() {
	make clean && make -j4
}

kernel_install_headers_arch() {
	sudo make INSTALL_HDR_PATH=$ARCH_ROOTFS/usr headers_install
}

kernel_install_headers_lava() {
	sudo make INSTALL_HDR_PATH=$LAVA_ROOTFS/usr headers_install
}

unset_kernel_vars() {
	unset KSRC
	unset KBUILD_OUTPUT
}

set_kernel_vars() {
	KSRC=$__OLD__KSRC
	KBUILD_OUTPUT=$__OLD__KBUILD_OUTPUT
}

stack_setup_env(){
	stack init && stack setup
}

v() {
	vim -p $@
}

# ALIASES
alias update='sudo pacman -Syu'
alias update_aur='yaourt -Syu'
alias lines='wc -l'
alias rm='rm -ri'
alias wifi='sudo wifi-menu'
alias stopa='sudo netctl stop-all'
alias gist='git status'
alias gibr='git branch -vv'
alias gich='git checkout'
alias findfile='find . -name'
alias exact_grep='grep -Ir'
alias emax='emacs -nw'
alias gpllr='git pull --rebase'
alias gpsh='git push'
alias c='cd'
alias gitree='git log --pretty=format:"%h %s" --graph'
alias gcc='clear && gcc'
alias gcc-win='clear && x86_64-w64-mingw32-gcc'
alias g++='clear && g++'
alias make='clear && make'
alias l='ls -la --color=always'
alias create_repo="$HOME/./.create_repo.sh"
alias kill-me='killall -u ferryk'
#alias quartus='./${QUARTUS_INSTALL_PATH}/quartus/quartus/bin/quartus'
alias shutdown='sudo netctl stop-all && sudo shutdown now'
alias reboot='sudo netctl stop-all && sudo reboot'

#BINDS
bind 'set mark-symlinked-directories on'

# Path to the bash it configuration
export BASH_IT="/home/ferryk/.bash_it"

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='zork'

# (Advanced): Change this to the name of your remote repo if you
# cloned bash-it with a remote other than origin such as `bash-it`.
# export BASH_IT_REMOTE='bash-it'

# Your place for hosting Git repos. I use this for private repos.
export GIT_HOSTING='git@git.domain.com'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Set Xterm/screen/Tmux title with only a short hostname.
# Uncomment this (or set SHORT_HOSTNAME to something else),
# Will otherwise fall back on $HOSTNAME.
#export SHORT_HOSTNAME=$(hostname -s)

# Set Xterm/screen/Tmux title with only a short username.
# Uncomment this (or set SHORT_USER to something else),
# Will otherwise fall back on $USER.
#export SHORT_USER=${USER:0:8}

# Set Xterm/screen/Tmux title with shortened command and directory.
# Uncomment this to set.
#export SHORT_TERM_LINE=true

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/djl/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# (Advanced): Uncomment this to make Bash-it reload itself automatically
# after enabling or disabling aliases, plugins, and completions.
# export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=1

# Load Bash It
source "$BASH_IT"/bash_it.sh
