" Basics
set nocompatible
set number
set textwidth=80
set mouse=n
syntax on
match error "\s$"

" Tab navigation
nnoremap <C-h> :tabprevious<CR>
nnoremap <C-l> :tabnext<CR>

" Moving tabs
nnoremap <C-k> :tabm +1<CR>
nnoremap <C-j> :tabm -1<CR>
